# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy React Frontend with PM2 and Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Ensure this runs on your self-hosted runner (AWS EC2)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js v22
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Use Node.js version 22

    - name: Install dependencies and build React app
      run: |
        cd /home/ubuntu/frontend/workspace/frontend_deploy/frontend_deploy  # Adjust the path to your project
        npm install
        npm run build

    - name: Deploy build to Nginx
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -r /home/ubuntu/frontend/workspace/frontend_deploy/frontend_deploy/build/* /var/www/html/
        sudo systemctl restart nginx

    - name: Start frontend with PM2
      run: |
        pm2 delete frontend || true  # Stop the process if it exists
        pm2 start "serve -s /var/www/html -l 3000" --name frontend
        pm2 save

    - name: Verify PM2 process
      run: pm2 list
