# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy React Frontend with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner on AWS EC2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies and build frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Deploy build to Nginx
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -r ./frontend/build/* /var/www/html/
        sudo systemctl restart nginx

    - name: Start PM2 process (Frontend)
      run: |
        pm2 start "serve -s /var/www/html -l 3000" --name frontend
        pm2 save
